name: Caller — java-service-openshift
on: { workflow_dispatch: {} }
jobs:
  run:
    uses: your-org/central-cicd-repo/.github/workflows/orchestrator.yml@v1.0.0
    with:
      pipeline_profile: java-service-openshift
      build-system: gradle
      java-version: '21'
      project-name: 'my-java-ocp-app'
      image-name: 'my-java-ocp-app'
      registry-server: docker.io
      registry-namespace: myuser
      sonar-project-key: 'org_ocp_app'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
