name: Cosign Sign
description: Sign an OCI image reference with cosign
inputs:
  image:
    required: true
  key:
    required: false
  password:
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if ! command -v cosign >/dev/null 2>&1; then
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
          chmod +x cosign && sudo mv cosign /usr/local/bin/cosign
        fi
        if [ -n "${{ inputs.key }}" ]; then
          echo "${{ inputs.key }}" > cosign.key
          COSIGN_PASSWORD="${{ inputs.password }}" cosign sign --key cosign.key "${{ inputs.image }}"
        else
          cosign sign "${{ inputs.image }}"
        fi
