name: Docker Push
description: Log in and push image to registry
inputs:
  registry:
    required: true
  username:
    required: true
  password:
    required: true
  source-image:
    required: true
  target-image:
    required: true
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - shell: bash
      run: |
        docker tag "${{ inputs.source-image }}" "${{ inputs.target-image }}"
        docker push "${{ inputs.target-image }}"
