name: 3 - Snyk Scan

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: 'ubuntu-latest'
      build-system:
        type: string
        required: true
      java-version:
        type: string
        default: '17'
      severity-threshold:
        type: string
        default: 'high'
      use-docker-action:
        type: boolean
        default: true
      jdk-major:
        type: string
        default: '17'
      snyk-slug:
        type: string
        default: ''
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk Open Source Scan (Test)
        continue-on-error: true
        run: |
          snyk test --sarif-file-output=snyk-oss.sarif --org=${{ inputs.snyk-slug }} || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source (Monitor for Dashboard)
        continue-on-error: true
        run: |
          snyk monitor --org=${{ inputs.snyk-slug }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
