name: 3 - Sonar (Quality Gate)
on:
  workflow_call:
    inputs:
      java-version: {type: string, required: true}
      sonar-project-key: {type: string, required: true}
    secrets:
      SONAR_TOKEN: {required: true}
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: ${{ inputs.java-version }} }
      - name: Sonar scan (placeholder)
        env: { SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} }
        run: echo "Run sonar-scanner for ${{ inputs.sonar-project-key }}"
