name: 3 - SonarCloud
on:
  workflow_call:
    inputs:
      runs-on: { type: string, default: 'ubuntu-latest' }
      java-version: { type: string, required: true }
      sonar-org: { type: string, required: true }
      sonar-project-key: { type: string, required: true }
    secrets:
      SONAR_TOKEN: { required: true }
jobs:
  sonar:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: ${{ inputs.java-version }} }
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ inputs.sonar-org }}
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
      # - name: Quality Gate (wait)
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   with:
      #     waitForQualityGate: true
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
