name: 3 - Static Checks

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      build-system:
        type: string
        required: true
      java-version:
        type: string
        required: true

jobs:
  static:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.build-system }}

      - name: Checkstyle
        shell: bash
        run: |
          if [ "${{ inputs.build-system }}" = "maven" ]; then
            mvn -B -ntp -DskipTests -Dcheckstyle.failOnViolation=false checkstyle:check
          else
            ./gradlew checkstyleMain spotbugsMain || echo "Configure Gradle plugins"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: |
            **/target/checkstyle-result.xml
            **/target/spotbugsXml.xml
            **/build/reports/checkstyle/**
            **/build/reports/spotbugs/**
          if-no-files-found: ignore
