name: 4 - Image Build

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      dockerfile-path:
        type: string
        required: true
      image-name:
        type: string
        required: false
    outputs:
      image-tag:
        value: ${{ jobs.build.outputs.image-tag }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      image-tag: ${{ steps.tag.outputs.value }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Resolve image name
        id: iname
        shell: bash
        run: |
          NAME="${{ inputs.image-name }}"
          if [ -z "$NAME" ]; then
            NAME="${{ github.repository }}"
          fi
          echo "value=$NAME" >> "$GITHUB_OUTPUT"

      - name: Build image (load locally)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: false
          load: true
          tags: ${{ steps.iname.outputs.value }}:${{ github.sha }}

      - name: Set tag output
        id: tag
        shell: bash
        run: echo "value=${{ steps.iname.outputs.value }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
