name: 4 - Image Push

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      image-ref:
        type: string
        required: true
      registry-server:
        type: string
        required: true
      registry-namespace:
        type: string
        required: true
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true
    outputs:
      registry-image:
        value: ${{ jobs.push.outputs.registry-image }}

jobs:
  push:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      registry-image: ${{ steps.out.outputs.value }}
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-server }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Retag & push
        shell: bash
        run: |
          TARGET="${{ inputs.registry-server }}/${{ inputs.registry-namespace }}/${{ inputs.image-ref }}"
          echo "Retagging to: $TARGET"
          docker tag "${{ inputs.image-ref }}" "$TARGET"
          docker push "$TARGET"

      - name: Output tag
        id: out
        shell: bash
        run: echo "value=${{ inputs.registry-server }}/${{ inputs.registry-namespace }}/${{ inputs.image-ref }}" >> "$GITHUB_OUTPUT"
